### ISSUE TITLE
  File "main.py", line 75, in gen_img_retry

### ISSUE THREAD

**Issue by cuimiao187561** [Sanster/text_renderer#77]
Retry gen_img: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "main.py", line 75, in gen_img_retry
    return renderer.gen_img(img_index)
  File "/opt/shakey/synetic/text_renderer/textrenderer/renderer.py", line 94, in gen_img
    word_img = self.noiser.apply(word_img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 38, in apply
    return noise_func(img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 58, in apply_uniform_noise
    row, col, channel = img.shape
ValueError: not enough values to unpack (expected 3, got 2)
Retry gen_img: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "main.py", line 75, in gen_img_retry
    return renderer.gen_img(img_index)
  File "/opt/shakey/synetic/text_renderer/textrenderer/renderer.py", line 94, in gen_img
    word_img = self.noiser.apply(word_img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 38, in apply
    return noise_func(img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 44, in apply_gauss_noise
    row, col, channel = img.shape
ValueError: not enough values to unpack (expected 3, got 2)
Retry gen_img: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "main.py", line 75, in gen_img_retry
    return renderer.gen_img(img_index)
  File "/opt/shakey/synetic/text_renderer/textrenderer/renderer.py", line 94, in gen_img
    word_img = self.noiser.apply(word_img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 38, in apply
    return noise_func(img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 69, in apply_sp_noise
    row, col, channel = img.shape
ValueError: not enough values to unpack (expected 3, got 2)
Retry gen_img: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "main.py", line 75, in gen_img_retry
    return renderer.gen_img(img_index)
  File "/opt/shakey/synetic/text_renderer/textrenderer/renderer.py", line 94, in gen_img
    word_img = self.noiser.apply(word_img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 38, in apply
    return noise_func(img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 69, in apply_sp_noise
    row, col, channel = img.shape
ValueError: not enough values to unpack (expected 3, got 2)
Retry gen_img: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "main.py", line 75, in gen_img_retry
    return renderer.gen_img(img_index)
  File "/opt/shakey/synetic/text_renderer/textrenderer/renderer.py", line 94, in gen_img
    word_img = self.noiser.apply(word_img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 38, in apply
    return noise_func(img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 58, in apply_uniform_noise
    row, col, channel = img.shape
ValueError: not enough values to unpack (expected 3, got 2)
Retry gen_img: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "main.py", line 75, in gen_img_retry
    return renderer.gen_img(img_index)
  File "/opt/shakey/synetic/text_renderer/textrenderer/renderer.py", line 94, in gen_img
    word_img = self.noiser.apply(word_img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 38, in apply
    return noise_func(img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 69, in apply_sp_noise
    row, col, channel = img.shape
ValueError: not enough values to unpack (expected 3, got 2)
Retry gen_img: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "main.py", line 75, in gen_img_retry
    return renderer.gen_img(img_index)
  File "/opt/shakey/synetic/text_renderer/textrenderer/renderer.py", line 94, in gen_img
    word_img = self.noiser.apply(word_img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 38, in apply
    return noise_func(img)
  File "/opt/shakey/synetic/text_renderer/textrenderer/noiser.py", line 58, in apply_uniform_noise
    row, col, channel = img.shape
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by swy0915** [comment]
main.py文件里

flags = parse_args()
flags.config_file = './configs/test.yaml' #增加
cfg = load_config(flags.config_file)

**Comment by swy0915** [comment]
我后来的解决办法是 修改noiser.py文件里的那些函数，在

        if len(img.shape) > 2:
            img = img
        else:
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

        row, col, channel = img.shape
